"""empty message

Revision ID: 146e21ca10e8
Revises: 2b3110c72289
Create Date: 2022-08-20 22:46:18.638036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146e21ca10e8'
down_revision = '2b3110c72289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('author_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
